stages:
  - test
  - deploy

image: chrissayon/python3.7_alpine:0.1

# Check python syntax
code_quality:
  stage: test
  script:
    - cd backend
    - flake8

unit_testing:
  stage: test
  script:
    - python3 -m pytest backend/tests