stages:
  # - build # Not used for python code
  - test
  - staging
  - deploy

# Check python syntax
code_quality:
  stage: test
  image: chrissayon/flask_ansible:0.2
  script:
    - cd backend
    - flake8 --max-line-length=90

# Unit testing
unit_testing:
  stage: test
  image: chrissayon/flask_ansible:0.2
  script:
    - python3 -m pytest backend/tests

deploy_dev:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: aws cloudformation create-stack --stack-name ec2 --template dev.yml

deploy_staging:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: aws cloudformation create-stack --stack-name ec2 --template stage.yml
  when: manual
  environment:
    name: staging
  only:
  - merge_requests

deploy_prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: aws cloudformation create-stack --stack-name ec2 --template prod.yml
  when: manual
  environment:
    name: production
  only:
  - master
