stages:
  - test
  - deploy

image: chrissayon/flask_ansible:1.0

# Check python syntax
code_quality:
  stage: test
  script:
    - cd backend
    - flake8

unit_testing:
  stage: test
  script:
    - python3 -m pytest backend/tests