stages:
  - test
  - deploy

image: chrissayon/python_flask:0.1

# Check python syntax
code_quality:
  stage: test
  script:
    - cd backend
    - flake8

unit_testing:
  stage: test
  script:
    - python3 -m pytest backend/tests