stages:
  - test
  - deploy

image: chrissayon/flask_ansible:0.1

# testings
# Check python syntax
code_quality:
  stage: test
  script:
    - cd backend
    - flake8 --max-line-length=90

unit_testing:
  stage: test
  script:
    - python3 -m pytest backend/tests