stages:
  # - build # Not used for python code
  - test
  - staging
  - deploy




# Check python syntax
code_quality:
  stage: test
  image: chrissayon/flask_ansible:0.2
  script:
    - cd backend
    - flake8 --max-line-length=90

    
# Unit testing
unit_testing:
  stage: test
  image: chrissayon/flask_ansible:0.2
  script:
    - python3 -m pytest backend/tests

# dev_server:
#   stage: test
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#   script: 
#     - 

# test:
#   stage: test
#   script: ./test
#   only:
#   - merge_requests

deploy:
  stage: deploy
  script: ./deploy
  only:
  - master
