stages:
  # - build # Not used for python code
  - test
  - staging
  - deploy

image: chrissayon/flask_ansible:0.2


# Check python syntax
code_quality:
  stage: test
  script:
    - cd backend
    - flake8 --max-line-length=90

    
# Unit testing
unit_testing:
  stage: test
  script:
    - python3 -m pytest backend/tests


# test:
#   stage: test
#   script: ./test
#   only:
#   - merge_requests

staging:
  stage: staging
  script: ./deploy
  only:
  - master
